name: Bug Report
description: Something isn't working
labels: [bug]
body:
  - id: validation
    type: checkboxes
    attributes:
      label: Before opening this issue, I ensure that...
      options:
      - label: I have read the [FAQ](https://github.com/RSDKModding/RSDKv4-Decompilation/blob/main/FAQ.md) and confirmed my issue is not mentioned in it.
        required: true
      - label: I have checked **both open and closed** issues and confirmed this bug has not already been reported.
        required: true
      - label: I am not asking for tech support (e.g. game closing on startup, error when trying to build, etc).
        required: true
      - label: I am not asking for modding support or reporting a bug in a specific mod; this bug either occurs without mods enabled or is directly related to the mod loader.
        required: true
      - label: This bug is not related to any unofficial fork/port of the decompilation, and any issues with those should be kept in the appropriate repository.
        required: true
  - id: expected-behavior
    type: input
    validations:
      required: true
    attributes:
      label: Expected Behavior
      description: What behavior is supposed to occur?
  - id: actual-behavior
    type: input
    validations:
      required: true
    attributes:
      label: Actual Behavior
      description: What actually happens?
  - id: repro-steps
    type: textarea
    validations:
      required: true
    attributes:
      label: Steps to Reproduce
      description: How can you reproduce the bug? Please give clear instructions.
      placeholder: |
        1. Do this
        2. Do that
        3. This happens
  - id: screenshots
    type: textarea
    validations:
      required: false
    attributes:
      label: Screenshots
      description: Provide screenshots if applicable.
  - id: log-file
    type: textarea
    validations:
      required: false
    attributes:
      label: Log File
      description: If EngineDebugMode is enabled in settings.ini, the decompilation will write to a log file named log.txt. You can provide it here if you believe it will be helpful.
  - id: decomp-version
    type: input
    validations:
      required: true
    attributes:
      label: Decompilation Version
      description: The decompilation version. If you built it manually or are using an autobuild, please specify the commit if possible.
  - id: game
    type: dropdown
    validations:
      required: true
    attributes:
      label: "Game"
      description: What game is being played?
      multiple: false
      options:
        - Sonic 1
        - Sonic 2
  - id: gameversion
    type: dropdown
    validations:
      required: true
    attributes:
      label: "Game Version"
      description: What version of the game is being played?
      multiple: false
      options:
        - Mobile (Sega Forever)
        - Mobile (Pre-Sega Forever)
        - Sonic Origins
  - id: gamerevision
    type: input
    validations:
      required: false
    attributes:
      label: Game Revision
      description: If you know the specific version number of the game, provide it here.
  - id: platform
    type: input
    validations:
      required: true
    attributes:
      label: Platform
      description: The platform/OS you're running the decompilation on.
  - id: comments
    type: textarea
    validations:
      required: false
    attributes:
      label: Additional Comments
      description: Provide any additional information if needed.
